# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_founded', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Dir')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField()),
                ('my_take', models.TextField()),
                ('node_image', models.ImageField(upload_to='')),
                ('Link_1', models.CharField(max_length=500)),
                ('Link_1_title', models.CharField(max_length=200)),
                ('Link_2', models.CharField(max_length=500)),
                ('Link_2_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Node_Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField()),
                ('current', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node_Dir'),
        ),
    ]
