# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(blank=True, default='', max_length=90)),
                ('link_url', models.CharField(blank=True, default='', max_length=300)),
                ('link_media', models.CharField(blank=True, default='', max_length=21)),
                ('link_media_url', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('home_page', models.CharField(default='', max_length=200)),
                ('date_founded', models.DateField(default='1965-08-08')),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('description', models.TextField()),
                ('fake_or_not', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('my_take', models.TextField()),
                ('head_image', models.ImageField(default='', upload_to='media/nodes')),
                ('foot_image', models.ImageField(default='', upload_to='media/nodes')),
                ('video_embed1', models.CharField(blank=True, default='', max_length=500)),
                ('video_embed2', models.CharField(blank=True, default='', max_length=500)),
                ('video_embed3', models.CharField(blank=True, default='', max_length=500)),
                ('hotness', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Node_Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=47)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_direc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node_Dir'),
        ),
        migrations.AddField(
            model_name='link',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Perspective'),
        ),
    ]
