# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_org',
            name='bias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Media_Bias_Dir',
        ),
        migrations.DeleteModel(
            name='Media_Country_Dir',
        ),
    ]
