# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_dir',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media_dir',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='Link_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='Link_1_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='Link_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='Link_2_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='headline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node_dir',
            name='current',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='node_dir',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
