# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0002_auto_20170109_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_dir',
        ),
        migrations.AddField(
            model_name='node',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Node_Dir',
        ),
    ]
