# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0003_auto_20170112_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_org',
            name='duplicate_bias',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media_org',
            name='duplicate_country',
            field=models.BooleanField(default=True),
        ),
    ]
