# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0003_auto_20161220_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
