# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0004_auto_20170112_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_image',
            field=models.ImageField(upload_to='nodanews_project/staticfiles/images/index'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='logo',
            field=models.ImageField(upload_to='nodanews_project/staticfiles/images/logos'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_image',
            field=models.ImageField(upload_to='nodanews_project/staticfiles/images/nodes'),
        ),
    ]
