# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0004_auto_20161229_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_org',
            name='home_page',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_image',
            field=models.ImageField(upload_to='nodanews/static/images/nodes'),
        ),
    ]
