# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0007_auto_20170103_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_org',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
