# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0007_auto_20170118_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[(b'Sou', b'Sources'), (b'Wik', b'Wikipedia'), (b'Vid', b'Video'), (b'Aca', b'Academic'), (b'Nod', b'Nodes')], default=b'Sou', max_length=10)),
                ('title_1', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_2', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_2', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_3', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_3', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_4', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_4', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_5', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_5', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_6', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_6', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_7', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_7', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_8', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_8', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_9', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_9', models.CharField(blank=True, default=b'url', max_length=500)),
                ('title_10', models.CharField(blank=True, default=b'title', max_length=200)),
                ('link_url_10', models.CharField(blank=True, default=b'url', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_10',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_10_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_1_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_2_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_3_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_4_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_5_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_6',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_6_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_7',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_7_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_8',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_8_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_9',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Link_9_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_title_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_title_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_title_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_title_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='academic_link_title_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_title_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_title_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_title_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_title_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_link_title_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_1_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_2_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='video_3_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_1',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_1_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_2',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_2_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_3',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_3_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_4',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_4_title',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_5',
        ),
        migrations.RemoveField(
            model_name='node',
            name='wiki_link_5_title',
        ),
        migrations.AlterField(
            model_name='index',
            name='index_image',
            field=models.ImageField(upload_to=b'media/index'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='logo',
            field=models.ImageField(upload_to=b'media/logos'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_image',
            field=models.ImageField(upload_to=b'media/nodes'),
        ),
        migrations.AddField(
            model_name='links',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node'),
        ),
    ]
