# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-04 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0008_media_org_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_org',
            name='country',
        ),
    ]
