# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0009_remove_media_org_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='title',
        ),
        migrations.AddField(
            model_name='media_dir',
            name='title',
            field=models.CharField(default='country/bias', max_length=100),
        ),
        migrations.AddField(
            model_name='media_org',
            name='date_posted',
            field=models.DateField(default='1965-08-08'),
        ),
        migrations.AddField(
            model_name='media_org',
            name='fake_or_not',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='node',
            name='video_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='video_1_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='video_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='video_2_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='video_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='video_3_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='video_embed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node_dir',
            name='title',
            field=models.CharField(default='country/subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='date_founded',
            field=models.DateField(default=''),
        ),
    ]
