# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0010_auto_20170126_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='node_headline',
            field=models.CharField(blank=True, default=b'node_ref-headline', max_length=200),
        ),
    ]
