# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0010_auto_20170105_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_org',
            name='date_founded',
            field=models.DateField(default='1965-08-08'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='fake_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
