# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0014_auto_20170127_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='academic_link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_link_url_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='academic_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_link_url_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_link_url_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='sources_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_link_url_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='video_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_link_url_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='wikipedia_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
