# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0015_auto_20170128_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_org',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
