# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0016_auto_20170208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='Link_1_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_21_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_22_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_23_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_2_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_31_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_32_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_33_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_3_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_41_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_42_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='Link_43_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='headline',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='headline_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='headline_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='headline_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
